### ISSUE TITLE
Missing constructor

### ISSUE THREAD

**Issue by bbacelar** [haniamr/simplefacebookclient#1]
Hi, The project is out of date.
On nuget version 1.2.0 there is a constructor whith 'retrycount' parameter.

**Comment by haniamr** [comment]
@bbacelar sorry for that, I've updated it now. 
Let me know if anything didn't work for you.

**Comment by bbacelar** [comment]
@haniamr When I tried to install the nuget package on .net Framework 4, I get this error: "Could not install package 'SimpleFacebookClient 1.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."
On the package page it says that it is compatible

**Comment by haniamr** [comment]
For some reason I couldn't get .Net 4 to work with the .Net Core project anymore, I'll look into it later today. If you managed to add it successfully, feel free to submit a PR.

Thanks!
